---
title: "Checkpoint 4 Duc Ngo Model Part2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Time series
```{r}
library(tidyverse)         # for reading in data, graphing, and cleaning
library(tidymodels)        # for modeling ... tidily
library(usemodels)         # for suggesting step_XXX() functions
library(glmnet)            # for regularized regression, including LASSO
library(naniar)            # for examining missing values (NAs)
library(lubridate)         # for date manipulation
library(moderndive)        # for King County housing data
library(vip)               # for variable importance plots
library(rmarkdown)         # for paged tables
library(dplyr)
library(janitor)
library(ggplot2)
library(dplyr)
library(bayesforecast)    # Bayes Forecasting (Playing around) 
library(bayesrules)
library(tidyverse)
library(rstanarm)
library(broom.mixed)
library(tidybayes)
library(bayesplot)
library(ggplot2)
library(tidymodels)
library(bayesmodels)
library(modeltime)
library(tidyverse)
library(timetk)
library(lubridate)
# This toggles plots from plotly (interactive) to ggplot (static)
interactive <- FALSE
```

### Dataset: 

```{r, echo=FALSE}
#Loading Dataset 
data <- read.csv("FINALDATASET.csv")
```

```{r}
#Scaling Variables of Interest
data <- data %>% 
  mutate(EARNINGS_Scaled = EARNINGS/1000000000,
         CASH_Scaled = CASH/1000000000,
         MARKET.CAP_Scaled = MARKET.CAP/1000000000,
         Earnings_next_year_Scaled = Earnings_next_year/1000000000,
         SALES_Scaled = SALES/1000000000)

#Adding Lagged Variables
data <- data %>% 
  group_by(COMPANY) %>%
  mutate(EARNINGS_1_YEAR_AGO = lead(EARNINGS_Scaled, n = 1), 
         EARNINGS_2_YEAR_AGO = lead(EARNINGS_Scaled, n = 2),
         EARNINGS_3_YEAR_AGO = lead(EARNINGS_Scaled, n = 3),
         EARNINGS_4_YEAR_AGO = lead(EARNINGS_Scaled, n = 4)) %>% 
  mutate(SALES_1_YEAR_AGO = lead(SALES_Scaled, n = 1),
         SALES_2_YEAR_AGO = lead(SALES_Scaled, n = 2),
         SALES_3_YEAR_AGO = lead(SALES_Scaled, n = 3),
         SALES_4_YEAR_AGO = lead(SALES_Scaled, n = 4))
         
```

```{r}
randomCompany <- read_csv("RandomCompnay.csv")
```

```{r}
randomCompany
```

```{r}
names(randomCompany)
```

```{r}
randomCompany <- randomCompany[,-1] 
```

### Bayesian Forecast: 

```{r}
library(bayesforecast)
```

```{r}
ts_model <- function(company) {
  newdata <- data %>% 
    filter(COMPANY == company) %>% 
    select(EARNINGS_Scaled) %>% 
    arrange(EARNINGS_Scaled)
  
  vector <- company$EARNINGS_Scaled
  
  myts <- ts(vector, start=c(1999), end=c(2021), frequency=1)

  sf1 = stan_sarima(ts = myts,order = c(1,1,1),seasonal = c(1,1,1),
                  prior_mu0 = student(mu = 0,sd = 1,df = 7))
  
}

ts_model(company = "AMZN")
```

```{r}
AMZN <- data %>% 
  filter(COMPANY == 'AMZN') %>% 
  select(EARNINGS_Scaled) %>% 
  arrange(EARNINGS_Scaled)

vector <- AMZN$EARNINGS_Scaled

myts <- ts(vector, start=c(1999), end=c(2021), frequency=1)

sf1 = stan_sarima(ts = myts,order = c(1,1,1),seasonal = c(1,1,1),
                  prior_mu0 = student(mu = 0,sd = 1,df = 7))
```

```{r}
data %>% 
  select(EARNINGS)
```

```{r}
AMZN <- data %>% 
  filter(COMPANY == 'AMZN') %>% 
  select(EARNINGS) 
  #arrange(EARNINGS_Scaled)
```

```{r}
sf1
```

```{r fig3}
check_residuals(sf1)
autoplot(forecast(object = sf1,h = 12))
```


