---
title: "Duc Ngo Test"
author: "Duc Ngo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)         # for reading in data, graphing, and cleaning
library(tidymodels)        # for modeling ... tidily
library(usemodels)         # for suggesting step_XXX() functions
library(glmnet)            # for regularized regression, including LASSO
library(naniar)            # for examining missing values (NAs)
library(lubridate)         # for date manipulation
library(moderndive)        # for King County housing data
library(vip)               # for variable importance plots
library(rmarkdown)         # for paged tables
library(dplyr)
library(janitor)
library(ggplot2)
theme_set(theme_minimal()) # my favorite ggplot2 theme :)
```

```{r}
library(readr)
library(readxl)
USA_TEST <- read_excel("USA_TEST.xlsx")
```


```{r}
S_and_P_500 <- USA_TEST %>% 
  filter(COMPANY %in% c('MMM', 'ABT', 'ABBV', 'ABMD', 'ACN', 'ATVI', 'ADBE', 'AMD', 'AAP', 'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 
		   'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT',
		   'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'ANTM', 'AON', 'AOS', 'APA', 'AAPL', 'AMAT', 'APTV', 'ADM',
		   'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'BKR', 'BLL', 'BAC', 'BBWI', 'BAX', 'BDX', 'BRK.B',
		   'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 'BK', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'CHRW',
		   'CDNS', 'CZR', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'CNC', 'CNP', 'CDAY',
		   'CERN', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CTXS', 'CLX',
		   'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'COP', 'ED', 'STZ', 'COO', 'CPRT', 'GLW', 'CTVA', 'COST', 'CTRA',
		   'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DISCA',
		   'DISCK', 'DISH', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DTE', 'DUK', 'DRE', 'DD', 'DXC', 'EMN', 'ETN', 'EBAY', 'ECL',
		   'EIX', 'EW', 'EA', 'EMR', 'ENPH', 'ETR', 'EOG', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ETSY', 'EVRG', 'ES', 'RE', 'EXC', 'EXPE',
		   'EXPD', 'EXR', 'XOM', 'FFIV', 'FB', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FE', 'FRC', 'FISV', 'FLT', 'FMC', 'F', 'FTNT', 'FTV',
		   'FBHS', 'FOXA', 'FOX', 'BEN', 'FCX', 'GPS', 'GRMN', 'IT', 'GNRC', 'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GL', 'GPN', 'GS',
		   'GWW', 'HAL', 'HBI', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM',
		   'HPQ', 'HUM', 'HBAN', 'HII', 'IEX', 'IDXX', 'INFO', 'ITW', 'ILMN', 'INCY', 'IR', 'INTC', 'ICE', 'IBM', 'IP', 'IPG', 'IFF', 'INTU',
		   'ISRG', 'IVZ', 'IPGP', 'IQV', 'IRM', 'JKHY', 'J', 'JBHT', 'SJM', 'JNJ', 'JCI', 'JPM', 'JNPR', 'KSU', 'K', 'KEY', 'KEYS', 'KMB',
		   'KIM', 'KMI', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LEG', 'LDOS', 'LEN', 'LLY', 'LNC', 'LIN', 'LYV', 'LKQ', 
		   'LMT', 'L', 'LOW', 'LUMN', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT',
		   'MRK', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI',
		   'NDAQ', 'NTAP', 'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NLSN', 'NKE', 'NI', 'NSC', 'NTRS', 'NOC', 'NLOK', 'NCLH', 'NRG', 'NUE',
		   'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'OKE', 'ORCL', 'OGN', 'OTIS', 'PCAR', 'PKG', 'PH', 'PAYX', 'PAYC', 'PYPL', 
		   'PENN', 'PNR', 'PBCT', 'PEP', 'PKI', 'PFE', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 
		   'PRU', 'PTC', 'PEG', 'PSA', 'PHM', 'PVH', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 
		   'RMD', 'RHI', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS',
		   'SNA', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STE', 'SYK', 'SIVB', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TGT', 'TEL',
		   'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TWTR', 'TYL', 'TSN', 'UDR',
		   'ULTA', 'USB', 'UAA', 'UA', 'UNP', 'UAL', 'UNH', 'UPS', 'URI', 'UHS', 'VLO', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VFC', 'VIAC', 
		   'VTRS', 'V', 'VNO', 'VMC', 'WRB', 'WAB', 'WMT', 'WBA', 'DIS', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WU', 'WRK', 'WY', 
		   'WHR', 'WMB', 'WLTW', 'WYNN', 'XEL', 'XLNX', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZION', 'ZTS'))
```

```{r}
S_and_P_500 %>% 
  filter(YEAR == 2009) %>% 
  group_by(COMPANY) %>% 
  arrange(desc(`MARKET CAP`))
```

```{r}
write.csv(S_and_P_500, "S_and_P_500.csv")
```



## Part 1: Data summary: 

```{r}
names(S_and_P_500)
length(unique(S_and_P_500$YEAR))
dim(S_and_P_500)
```


#What our Dataset looks like 
```{r}
head(S_and_P_500)
```

#These are the companies we have all 23 years of data. 
```{r}
Full_Company <- S_and_P_500 %>% 
  group_by(COMPANY, YEAR) %>% 
  summarize() %>% 
  count(COMPANY) %>% 
  filter(n == 23)

Full_Company <- (Full_Company$COMPANY)

length(Full_Company)

FULL_TEST <- S_and_P_500 %>% 
  filter(COMPANY %in% Full_Company) 
```

We have 900 companies that have all 23 years of data. 

#Total number of companies 
```{r}
S_and_P_500 %>% 
  group_by(COMPANY, YEAR) %>% 
  summarize() %>% 
  count(COMPANY)
```


#These are the the total number of years we have
```{R}
tabyl(S_and_P_500$YEAR) %>% 
  ggplot(aes(x= `S_and_P_500$YEAR`, y = n)) +
  geom_line()+
  xlab("")+
  ylab("") + 
  labs(title = "Number of companies within the period") + 
  theme_minimal()
```

```{r}
S_and_P_500 %>% 
  filter(YEAR == '2020') %>% 
  group_by(COMPANY) %>% 
  arrange(desc(`MARKET CAP`))
```

Generally, as the years go on, more companies join our dataset. 

```{r}
FULL_TEST[FULL_TEST == 0] <- NA
FULL_TEST <- FULL_TEST %>% select(-`Sell`)
FULL_TEST <- na.omit(FULL_TEST)

test <- FULL_TEST %>% 
  group_by(COMPANY, YEAR) %>% 
  summarize() %>% 
  count(COMPANY) %>% 
  filter(n == 23) 

colSums(is.na(FULL_TEST))
```

There are a total of 7004 different companies in our data set. 


II/ Visualization: 

```{r}
meanUSA <- USA_TEST %>% 
  group_by(YEAR) %>% 
  summarise(meanMarket_cap = mean(`MARKET CAP`), 
            meanEarnings = mean(EARNINGS), 
            meanCOGS = mean(COGS), 
            meanSALES = mean(SALES), 
            meanCASH = mean(CASH), 
            meanInvestments = mean(INVESTMENTS), 
            meanReceivable = mean(RECEIVABLE), 
            meanInventory = mean(INVENTORY), 
            meanDebts = mean(DEBTS)) 
```


```{r}
sumUSA <- USA_TEST %>% 
  group_by(YEAR) %>% 
  summarise(sumMarket_cap = sum(`MARKET CAP`), 
            sumEarnings = sum(EARNINGS), 
            sumCOGS = sum(COGS), 
            sumSALES = sum(SALES), 
            sumCASH = sum(CASH), 
            sumInvestments = sum(INVESTMENTS), 
            sumReceivable = sum(RECEIVABLE), 
            sumInventory = sum(INVENTORY), 
            sumDebts = sum(DEBTS)) 
```

```{r}
sumUSA %>% 
  ggplot(aes(x = YEAR, y = sumMarket_cap)) + geom_line()
```

```{r}
meanUSA %>% 
  ggplot(aes(x = YEAR, y = meanEarnings)) + geom_point()
```




```{r}
meanUSA %>% 
  ggplot(aes(x = YEAR, y = meanCOGS)) + geom_point()
```

```{r}
meanUSA %>% 
  ggplot(aes(x = YEAR, y = meanSALES)) + geom_point()
```

```{r}
meanUSA %>% 
  ggplot(aes(x = YEAR, y = meanCASH)) + geom_point()
```

```{r}
meanUSA %>% 
  ggplot(aes(x = YEAR, y = meanInvestments)) + geom_point()
```


```{r}
ggplot(USA_TEST, aes(x = EARNINGS)) + 
  geom_density()
```





