---
title: "NickPart2"
author: "NicholasDi"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)         # for reading in data, graphing, and cleaning
library(tidymodels)        # for modeling ... tidily
library(usemodels)         # for suggesting step_XXX() functions
library(glmnet)            # for regularized regression, including LASSO
library(naniar)            # for examining missing values (NAs)
library(lubridate)         # for date manipulation
library(moderndive)        # for King County housing data
library(vip)               # for variable importance plots
library(rmarkdown)         # for paged tables
library(dplyr)
library(janitor)
# Load packages
library(bayesrules)
library(tidyverse)
library(rstanarm)
library(broom.mixed)
library(tidybayes)
library(bayesplot)
library(ggplot2)
theme_set(theme_minimal()) # my favorite ggplot2 theme :)
```

```{r}
library(readr)
data <- read_csv("S_and_P_500.csv")
data_2 <- read.csv("FINALDATASET.csv")
```

```{r}
data_2 %>% 
  group_by(Sector, YEAR) %>% 
  summarize(count = n()) %>% 
  summarize(mean = mean(count)) %>% ggplot(aes(y=mean, x = Sector, fill = Sector))+
  geom_col(position = "dodge") + 
  theme_minimal()+
  theme(axis.title.x = element_blank())
```
#Top 50 Companies 
```{r}
temp <- data_2 %>% 
  group_by(COMPANY) %>% 
  summarize(count = n(), 
            mean_MC = mean(MARKET.CAP)) %>% 
  filter(count == 23) %>% 
  arrange(desc(mean_MC)) %>% 
  head(50)
temp <- temp$COMPANY

data_2 <- data_2 %>%  
  filter(COMPANY %in% temp)  
```

#Relationship between EARNINGS and SALES among top 50 companies MarketCap 

```{r}
data_2 %>% 
  ggplot(aes(y = EARNINGS, x= SALES, color = Sector))+
  geom_point(alpha = 0.20)+
  geom_smooth(method = 'lm', formula = y ~ x)+
  theme_minimal()+
  ggtitle("Sales and Earnings Relationship by Sector \n Among top 50 Companies by Market Cap")
```



```{r}
# Simulate the posterior
easy_model <- stan_glm(
  EARNINGS ~ SALES, data = data,
  family = gaussian,
  prior_PD = FALSE,
  chains = 4, iter = 5000*2, seed = 84735, refresh = 0)
```

```{r}
data %>%
  add_fitted_draws(easy_model, n = 200, color = "blue") %>%
  ggplot(aes(x = EARNINGS, y = SALES)) + #flip x and y??
    geom_line(aes(y = .value, group = .draw), alpha = 0.15) + 
    geom_point(data = data)
```

```{r}
tidy(easy_model, conf.int = TRUE, conf.level = 0.95)
```
```{r}
ggplot(data, aes(x = EARNINGS, y = SALES, group = COMPANY)) + 
    geom_smooth(method = "lm", se = FALSE)
```

```{r}
top50Companies <- read.csv("TOP_50_COMPANIES.csv")
```

```{r}
# Simulate the prior model
model_1_prior_with_hiar <- stan_glmer(
  EARNINGS ~ SALES + (1 | COMPANY), data = top50Companies, 
  family = gaussian,
  chains = 4, iter = 5000*2, seed = 84735, 
  prior_PD = TRUE)

tidy(model_1_prior_with_hiar, conf.int = TRUE)

model_1_post_with_hiar <- stan_glmer(
  EARNINGS ~ SALES + (1 | COMPANY), data = top50Companies, 
  family = gaussian,
  chains = 4, iter = 5000*2, seed = 84735, 
  prior_PD = FALSE)

tidy(model_1_post_with_hiar, conf.int = TRUE)


# Check out the prior specifications
prior_summary(model_1_prior_with_hiar)
```

```{r}
prior_summary(model_1_prior_with_hiar)
```







