---
title: "NolanTest"
author: "Nolan Meyer"
date: "11/9/2021"
output: html_document
---

```{r}
library(bayesrules)
library(tidyverse)
library(rstanarm)
library(broom.mixed)
library(tidybayes)
library(forcats)
library(bayesplot)

library(readxl)
USA_TEST <- read_excel("USA_TEST.xlsx")
```

```{r}
names(USA_TEST)
length(unique(USA_TEST$YEAR))
dim(USA_TEST)
head(USA_TEST)
```

```{r}
USA_TEST %>% 
  ggplot(aes(x = SALES, y = EARNINGS, group = COMPANY)) +
  geom_point() +
  theme_classic()
```

```{r}
meanUSA <- USA_TEST %>% 
  group_by(YEAR) %>% 
  summarise(meanMarket_cap = mean(`MARKET CAP`), 
            meanEarnings = mean(EARNINGS), 
            meanCOGS = mean(COGS), 
            meanSALES = mean(SALES), 
            meanCASH = mean(CASH), 
            meanInvestments = mean(INVESTMENTS), 
            meanReceivable = mean(RECEIVABLE), 
            meanInventory = mean(INVENTORY), 
            meanDebts = mean(DEBTS)) 
```

```{r}
USA_TEST %>% 
  ggplot(aes(x = COGS, y = EARNINGS)) + 
  geom_point()
```

```{r}
USA_TEST %>% 
  ggplot(aes(x = CASH, y = EARNINGS)) + 
  geom_smooth(method = "lm") +
  geom_point()
```